services:
  api:
    build: ./TodoApi
    container_name: todo_api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1403
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./frontend
    container_name: todo_web
    ports:
      - "8081:80"
    depends_on:
      - api

volumes:
  db_data: